# Generated by Django 4.1.5 on 2023-01-26 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuserowner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner_store', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='storemachines',
            name='machine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_machine', to='app_store.machine', verbose_name='Machine'),
        ),
        migrations.AddField(
            model_name='storemachines',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_store', to='app_store.store', verbose_name='Store'),
        ),
        migrations.AddField(
            model_name='machinehistory',
            name='destination_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_destination_store', to='app_store.storeuserowner', verbose_name='Destination Store'),
        ),
        migrations.AddField(
            model_name='machinehistory',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_machine', to='app_store.machine', verbose_name='Machine'),
        ),
        migrations.AddField(
            model_name='machinehistory',
            name='origin_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_origin_store', to='app_store.storeuserowner', verbose_name='Origin Store'),
        ),
        migrations.AddField(
            model_name='machine',
            name='psp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_psp', to='app_store.psp', verbose_name='PSP'),
        ),
    ]
