# Generated by Django 4.1.5 on 2023-01-27 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^{?(0?9[0-9]{9,9}}?)$', 'Invalid Mobile Number Format.')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=11, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('CEO', 'CEO'), ('EXP', 'Expert'), ('STK', 'Storekeeper'), ('AGN', 'Agent'), ('SUP', 'Supporter')], default='SUP', max_length=3, verbose_name='Position'),
        ),
    ]
