# Generated by Django 4.1.5 on 2023-01-27 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_user_mobile_number_alter_user_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^{?(0?9[0-9]{9,9}}?)$', 'Invalid Mobile Number Format.')], verbose_name='Mobile Number'),
        ),
    ]
