# Generated by Django 4.1.5 on 2023-02-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creator_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
